name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Check ncd_calculator Directory
      run: ls -la .
    - name: Change to ncd_calculator
      run: cd ncd_calculato
      
    - name: Install Dependencies
      run: npm ci
    - name: Build Project
      run: npm run build --if-present

    - name: Run Tests
      run: npm test
